// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZCPFE-ZJFj_nkGk_4-S6C8XVwE3USasQ',
    appId: '1:621136941396:web:018493dfe38350ed9778c1',
    messagingSenderId: '621136941396',
    projectId: 'diet-app-ad560',
    authDomain: 'diet-app-ad560.firebaseapp.com',
    storageBucket: 'diet-app-ad560.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu1s79ghpvs_jcYp3Ppi1egZo6Gqbw_9w',
    appId: '1:621136941396:android:d8c2711066cbc8d39778c1',
    messagingSenderId: '621136941396',
    projectId: 'diet-app-ad560',
    storageBucket: 'diet-app-ad560.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm3U7wsQeGntWh-IP9Q-jMQvTkY0NbAgg',
    appId: '1:621136941396:ios:65251e7dcc2df11a9778c1',
    messagingSenderId: '621136941396',
    projectId: 'diet-app-ad560',
    storageBucket: 'diet-app-ad560.firebasestorage.app',
    iosBundleId: 'com.example.dietApp',
  );
}
